version: '2.1'

services:
  
  aquappdatabase:
    image: "mongo:4.0.5"
    ports:
      - 27017:27017
    volumes:
      - ./databasenew:/data/db
      - ./imports:/imports
      - ./backups:/backups

  api:
    build: ./api
    ports:
      - 8080:3000
    depends_on:
      - aquappdatabase

  aquapp:
    build: ./aquapp
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
  
  grafana:
    image: "grafana/grafana"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana-storage:/var/lib/grafana
  
  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
      - 8090:8090
    depends_on:
      - grafana
